### PR TITLE
Fix var scoping issue

### PR DESCRIPTION
**Pull request by sjdaniels**
Should fix this exception I see every once in a while...

`lucee.runtime.exp.ExpressionException: Key [619] doesn't exist in Native Array
	at lucee.runtime.util.VariableUtilImpl.get(VariableUtilImpl.java:300)
	at lucee.runtime.PageContextImpl.get(PageContextImpl.java:1432)
	at commons.modules.cbi18n.models.i18n_cfc$cf.udfCall7(/home/deploy/mergernetwork.regional/production/commons/modules/cbi18n/models/i18n.cfc:897)
	at commons.modules.cbi18n.models.i18n_cfc$cf.udfCall(/home/deploy/mergernetwork.regional/production/commons/modules/cbi18n/models/i18n.cfc)`

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks @sjdaniels !  I don't have write access to this repo, so @lmajano will need to review and merge when he's done traveling home from CF Summit.

**Comment by lmajano** [comment]
hmm, I can't see the changes, are the line breaks changed or something?

**Comment by bdw429s** [comment]
@lmajano You don't see this message:
> 1 addition, 1 deletion not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by lmajano** [comment]
@bdw429s I did, but I can't see the diff even locally, seems like all line endins are changed

**Comment by sjdaniels** [comment]
I don't get it, no mater what I do I can't get this diff to come out right. All I am trying to do is add the line:

`var i = 0;`

At line 878, in the function `getTzQuery`. I tried Unix, Windows and Max OS in Sublime's Line Endings setting, also tried using a plain text editor and editing in nano.

**Comment by elpete** [comment]
I had the same issue on the coldbox-templates.  I used `mac2unix` to fix the line endings and then the diffs worked.

**Comment by sjdaniels** [comment]
@elpete thanks but that didn't seem to do it either... I used this: https://github.com/jhbadger/scripts/blob/master/mac2unix

Did you have another version from somewhere else maybe?

**Comment by elpete** [comment]
Hmmm...I believe it was preinstalled on my Mac.

**Comment by elpete** [comment]
I just opened my own pull request to fix the line endings. ¯\_(ツ)_/¯

https://github.com/coldbox-modules/cbox-i18n/pull/23

**Comment by bdw429s** [comment]
@lmajano I used WinMerge to locally review the two files and can confirm that it looks good.  Can you please merge this pull or give me permissions to do it?

**Comment by jclausen** [comment]
@bdw429s :  I fixed your permission on the org.  You should be able to merge for all modules in this namespace now.

**Comment by sjdaniels** [comment]
Thanks all!

**Pull request merged**
